<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="TalentRecruit" duration-ms="128132" started-at="2022-01-10T13:17:48Z" finished-at="2022-01-10T13:19:56Z">
    <groups>
    </groups>
    <test name="TalentRecruit Application Testing" duration-ms="128132" started-at="2022-01-10T13:17:48Z" finished-at="2022-01-10T13:19:56Z">
      <class name="com.TalentRecruit.testCases.TC_LoginTest_Multiple_DataSet">
        <test-method status="PASS" signature="setup(java.lang.String, java.lang.String)[pri:0, instance:com.TalentRecruit.testCases.TC_LoginTest_Multiple_DataSet@1554909b]" name="setup" is-config="true" duration-ms="3297" started-at="2022-01-10T13:17:48Z" finished-at="2022-01-10T13:17:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[large]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="loginTestMultipleSet(java.lang.String, java.lang.String)[pri:0, instance:com.TalentRecruit.testCases.TC_LoginTest_Multiple_DataSet@1554909b]" name="loginTestMultipleSet" duration-ms="61140" started-at="2022-01-10T13:17:52Z" data-provider="LoginData" finished-at="2022-01-10T13:18:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[arunpartap05@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Aps@0001]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestMultipleSet -->
        <test-method status="FAIL" signature="loginTestMultipleSet(java.lang.String, java.lang.String)[pri:0, instance:com.TalentRecruit.testCases.TC_LoginTest_Multiple_DataSet@1554909b]" name="loginTestMultipleSet" duration-ms="60718" started-at="2022-01-10T13:18:53Z" data-provider="LoginData" finished-at="2022-01-10T13:19:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[arunpartap05@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Aps@0002]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.TalentRecruit.testCases.TC_LoginTest_Multiple_DataSet.loginTestMultipleSet(TC_LoginTest_Multiple_DataSet.java:115)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestMultipleSet -->
        <test-method status="FAIL" signature="loginTestMultipleSet(java.lang.String, java.lang.String)[pri:0, instance:com.TalentRecruit.testCases.TC_LoginTest_Multiple_DataSet@1554909b]" name="loginTestMultipleSet" duration-ms="581" started-at="2022-01-10T13:19:54Z" data-provider="LoginData" finished-at="2022-01-10T13:19:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[f.mmm@coe.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Aps@0002]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.TalentRecruit.testCases.TC_LoginTest_Multiple_DataSet.loginTestMultipleSet(TC_LoginTest_Multiple_DataSet.java:127)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestMultipleSet -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.TalentRecruit.testCases.TC_LoginTest_Multiple_DataSet@1554909b]" name="teardown" is-config="true" duration-ms="1357" started-at="2022-01-10T13:19:55Z" finished-at="2022-01-10T13:19:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.TalentRecruit.testCases.TC_LoginTest_Multiple_DataSet -->
    </test> <!-- TalentRecruit Application Testing -->
  </suite> <!-- TalentRecruit -->
</testng-results>
